require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '13.0'

target 'AddReactNativeDemo' do
  use_react_native!(hermes_enabled: true, fabric_enabled: true)

  pod 'Alamofire'
end
