platform :ios, '13.0'

flutter_application_path = '../mobile_forum_demo_shared'
load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')

target 'EmbedFlutterDemoIOS' do
  install_all_flutter_pods(flutter_application_path)

end

post_install do |installer|
  flutter_post_install(installer) if defined?(flutter_post_install)
end

